### ISSUE TITLE
Unknown types on latest westend

### ISSUE THREAD

**Issue by octol** [maxsam4/fork-off-substrate#4]
Tried this on latest westend and I'm getting errors related to unknown types

> 2021-05-13 08:14:50        API/INIT: Api will be available in a limited mode since the provider does not support subscriptions
> 2021-05-13 08:14:51        REGISTRY: Unable to resolve type Outcome, it will fail on construction
> 2021-05-13 08:14:51        REGISTRY: Unable to resolve type PalletId, it will fail on construction
> 2021-05-13 08:14:51        REGISTRY: Error: Cannot construct unknown type PalletId
> 2021-05-13 08:14:51        API/INIT: Error: FATAL: Unable to initialize the API: createType(PalletId):: Cannot construct unknown type PalletId
> 2021-05-13 08:14:51        API/INIT: Error: createType(PalletId):: Cannot construct unknown type PalletId

**Comment by maxsam4** [comment]
I've updated the polkadot.js version. That should fix the issue. Please do `git pull && npm install` and try again.

**Comment by octol** [comment]
Thanks! Can confirm it's working now!
