### ISSUE TITLE
Can this script backup the whole blockchain?

### ISSUE THREAD

**Issue by xcaptain** [maxsam4/fork-off-substrate#57]
I tried to run this script, but I found I can only backup the current state, all the blocks since block 1 in the fork chain are different with the original chain, just want to make sure can this script backup the whole blockchain?

**Comment by lucgerrits** [comment]
Hi, what was the answer ?

**Comment by xcaptain** [comment]
The answer is this script can only backup the state, if you don't mind the state of your old chain saved the genesis block of the new chain, you can give it a try.

**Comment by lucgerrits** [comment]
Oh I see, thanks a lot.
So you can start a new chain based on the current state of the old chain, but without the history of the old chain.
Do you know if its possible to fork the old chain, keeping the old chain history/data, and forcing the fork with different data (ex: changing the validator set or something else) ?
